### ISSUE TITLE
DevOps integration

### ISSUE THREAD

**Issue by xaiyadev** [xaiyadev/dotfiles#10]
To keep my code clean, and make sure that all my configurations are working on every system.

## TODO
- [ ] install a pipeline into my github repository
- [ ] link the pipeline to a tool (e.g (drone)[https://www.drone.io/])
- [ ] configurate the tool/pipeline correctly
